//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Interface.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrevista
    {
        public int IdEntrevista { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Turno { get; set; }
        public short Asiste { get; set; }
        public short Valoracion { get; set; }
    }
}
